# Use the official MySQL 8.0 image from Docker Hub
FROM mysql:8.0

# Set environment variables for MySQL
ENV MYSQL_ROOT_PASSWORD=DVADMIN3
ENV MYSQL_DATABASE=django-vue3-admin
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=DVADMIN3

# Copy any custom configuration files, if needed
# COPY ./my.cnf /etc/mysql/my.cnf

# Expose the default MySQL port
EXPOSE 3306

# Add any additional setup or initialization scripts
# COPY ./init.sql /docker-entrypoint-initdb.d/
