# Use the official Redis image from Docker Hub
FROM redis:latest

# Set the working directory
WORKDIR /data

# Expose the default Redis port
EXPOSE 6379

# Start the Redis server
CMD ["redis-server"]
